# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snipgo < Formula
  desc "Local-First Snippet Manager"
  homepage "https://github.com/atobaum/snipgo"
  version "0.0.1"
  license "MIT"

  depends_on "fzf"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/atobaum/snipgo/releases/download/v0.0.1/snipgo_0.0.1_darwin_amd64.tar.gz"
    sha256 "c979e300d3c555c44229ec891dd179a36a1f685b1fa35646d73fe67c8f1ca033"

    def install
      bin.install "snipgo"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/atobaum/snipgo/releases/download/v0.0.1/snipgo_0.0.1_darwin_arm64.tar.gz"
    sha256 "b2dfd4f37736b62dbdf8ba6c2ee24e1dcc64c18efe7659ec20c42405955a7a82"

    def install
      bin.install "snipgo"
    end
  end

  test do
    system "#{bin}/snipgo", "--version"
  end
end
