# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snipgo < Formula
  desc "Local-First Snippet Manager"
  homepage "https://github.com/atobaum/snipgo"
  version "0.0.3"
  license "MIT"

  depends_on "fzf"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/atobaum/snipgo/releases/download/v0.0.3/snipgo_0.0.3_darwin_amd64.tar.gz"
    sha256 "0d4cff2ad905d8c546c21f3325cbfd9c056273b326877867d4779becdb3e4475"

    def install
      bin.install "snipgo"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/atobaum/snipgo/releases/download/v0.0.3/snipgo_0.0.3_darwin_arm64.tar.gz"
    sha256 "cfde46dfddbd587768cfe8a41b2c0bcc9b96411c04043e99a17d9ac8ef92f233"

    def install
      bin.install "snipgo"
    end
  end

  test do
    system "#{bin}/snipgo", "--version"
  end
end
