# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snipgo < Formula
  desc "Local-First Snippet Manager"
  homepage "https://github.com/atobaum/snipgo"
  version "0.0.2"
  license "MIT"

  depends_on "fzf"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/atobaum/snipgo/releases/download/v0.0.2/snipgo_0.0.2_darwin_amd64.tar.gz"
    sha256 "a4fcb7c06f7aee7e8b808e8dbafdce812010f32a3bf7b6c0c05291a9558cc79a"

    def install
      bin.install "snipgo"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/atobaum/snipgo/releases/download/v0.0.2/snipgo_0.0.2_darwin_arm64.tar.gz"
    sha256 "802d10619cbaf6ddc1ddd181ab558d154d953e99ca14ced406b7306c9aab4f0e"

    def install
      bin.install "snipgo"
    end
  end

  test do
    system "#{bin}/snipgo", "--version"
  end
end
